/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.frontend;

import org.example.controladores.SolicitudesControlador;
import org.example.modelos.Solicitud;
import java.util.Date;

/**
 *
 * @author boika_fire
 */
public class SolicitudesFormulario extends javax.swing.JFrame {

    private final SolicitudesControlador solicitudesControlador;

    /**
     * Creates new form SolicitudesFormulario
     */
    public SolicitudesFormulario(SolicitudesControlador solicitudesControlador) {
        initComponents();
        this.solicitudesControlador = solicitudesControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroSolicitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaSolicitud = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoSolicitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreSolicitud = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salarioSolicitud = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        direccionSolicitud = new javax.swing.JTextField();
        guardarSolicitud = new javax.swing.JButton();
        cancelarSolicitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nueva Solicitud");

        jLabel2.setText("Numero de Solicitud:");

        numeroSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroSolicitudActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Salario");

        salarioSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioSolicitudActionPerformed(evt);
            }
        });

        jLabel7.setText("Direccion:");

        guardarSolicitud.setText("Guardar");
        guardarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarSolicitudActionPerformed(evt);
            }
        });

        cancelarSolicitud.setText("Cancelar");
        cancelarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarSolicitud)
                                .addGap(26, 26, 26)
                                .addComponent(cancelarSolicitud))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(numeroSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(fechaSolicitud)
                                .addComponent(tipoSolicitud)
                                .addComponent(nombreSolicitud)
                                .addComponent(salarioSolicitud)
                                .addComponent(direccionSolicitud)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salarioSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(direccionSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarSolicitud)
                    .addComponent(cancelarSolicitud))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salarioSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioSolicitudActionPerformed

    private void guardarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarSolicitudActionPerformed
        Solicitud solicitud = new Solicitud(
            Integer.parseInt(numeroSolicitud.getText()),
            new Date(fechaSolicitud.getText()),
            tipoSolicitud.getText(),
            nombreSolicitud.getText(),
            Double.parseDouble(salarioSolicitud.getText()),
            direccionSolicitud.getText()
        );
        solicitudesControlador.crearSolicitud(solicitud);
    }//GEN-LAST:event_guardarSolicitudActionPerformed

    private void cancelarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarSolicitudActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarSolicitudActionPerformed

    private void numeroSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroSolicitudActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarSolicitud;
    private javax.swing.JTextField direccionSolicitud;
    private javax.swing.JTextField fechaSolicitud;
    private javax.swing.JButton guardarSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreSolicitud;
    private javax.swing.JTextField numeroSolicitud;
    private javax.swing.JTextField salarioSolicitud;
    private javax.swing.JTextField tipoSolicitud;
    // End of variables declaration//GEN-END:variables
}
